// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayvlvkwixkkjkysgeetj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dmx2a3dpeGtramt5c2dlZXRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMjM1MDQsImV4cCI6MjA3Nzc5OTUwNH0.YxqijUedPXJawt4TY8YBs2R6GDToc35rdEQoMo2B36Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});